Enhancement: Throw a SessionTimeOutException to notify frontend
Without the remember me option sessions can time out and when the user
opens the notificationpopup it will result in following error:

Exception: java.lang.NumberFormatException:Wrong nubmer

Avoid this exception and make sure that the Account navigation item is changed
to "Log In" and fire a DisplayNotificationEvent